DROP TABLE USUARIOS;
DROP TABLE PACOTES;

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(255),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
   
);



CREATE TABLE PACOTES (
    ID_PACOTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    CODIGO_RASTREAMENTO VARCHAR(50) UNIQUE NOT NULL,
    DESTINO VARCHAR(200) NOT NULL,
    STATUS VARCHAR(200) NOT NULL,
    DATA_ENVIO DATE NOT NULL,
    DATA_ENTREGA DATE,
    
    FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO)
);



INSERT INTO USUARIOS (NOME, CPF, EMAIL, TELEFONE, ENDERECO, CIDADE, ESTADO)
VALUES
('CLARA', '123456', 'CLARA@GMAIL.COM', '27999998888', 'RUA DB HOWARD, 123', 'VITÓRIA', 'ES'),
('ROBOCOP', '987652', 'ROBOCOP@GMAIL.COM', '27988887777', 'AV. ODEIOJAVA, 456', 'SERRA', 'ES');

INSERT INTO PACOTES (ID_USUARIO, CODIGO_RASTREAMENTO, DESTINO, STATUS, DATA_ENVIO, DATA_ENTREGA)
VALUES
(1, 'DF7AG4AG98D4', 'SÃO PAULO - SP', 'EM TRÂNSITO', '2025-10-10', '2024-10-12'),
(2, 'AFGKANON885',  'RIO DE JANEIRO - RJ', 'ENTREGUE', '2025-09-28', '2025-10-02');



SELECT COUNT(1) AS TOTAL_USUARIOS FROM USUARIOS;
SELECT COUNT(1) AS TOTAL_PACOTES FROM PACOTES;





